// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jscendxyylrjyrynkwmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzY2VuZHh5eWxyanlyeW5rd21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyODc5MDcsImV4cCI6MjA4Njg2MzkwN30.zCuoU9EHR26slBTHs-IneIgq4y4umA5oo6O7pbBIz9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});